swagger:
  resourcePackage: com.assignment.resources

server:
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

base-directory: /Users/arun/search-directory

